name: ci
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: dtolnay/rust-toolchain@stable
      - run: corepack enable
      - run: pnpm i
      - run: pnpm lint-check
      - run: pnpm tsc
      - run: pnpm test
      # https://github.com/tauri-apps/tauri-action
      - run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - run: pnpm build
      - uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          name: 0.0.0-pre.${{ github.sha }}
          tag_name: 0.0.0-pre.${{ github.sha }}
          files: src-tauri/target/release/bundle/appimage/*.AppImage
